-- ============================================================
-- MicroBuild — Project Pipeline Foundation
-- ============================================================
-- Safe to run multiple times: all statements use
--   ADD COLUMN IF NOT EXISTS  (no-op if column exists)
--   DROP NOT NULL             (idempotent)
--
-- Run in Supabase SQL editor AFTER schema.sql has been applied.
--
-- WHAT THIS MIGRATION DOES:
--   1. Expands `orders` for full project pipeline tracking
--   2. Expands `build_packets` with launch checklist + AI summary
--   3. Expands `deliverables` with GitHub URL + status + profile link
--   4. Adds DEV-ONLY RLS policies (clearly marked UNSAFE)
--
-- DO NOT run section 4 in production — replace with proper auth checks.
-- ============================================================


-- ─── 1. orders — expand for project pipeline ─────────────────────────────────

-- Allow orders without a linked auth user (guests can have requests converted)
ALTER TABLE public.orders
  ALTER COLUMN buyer_id DROP NOT NULL;

-- Pipeline status: richer than the legacy `status` field
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS order_status text NOT NULL DEFAULT 'draft';

-- Payment status (separate from order workflow)
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS payment_status text NOT NULL DEFAULT 'unpaid';

-- Human-readable project title
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS project_title text;

-- Mirrors build type / MicroBuild category for this order
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS project_type text;

-- Admin-only internal notes
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS admin_notes text;

-- Fee and payout amounts (text so we can store "$150–$300" ranges too)
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS microbuild_fee text;
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS creator_payout text;


-- ─── 2. build_packets — add missing fields ────────────────────────────────────

-- Steps to follow after the build is approved
ALTER TABLE public.build_packets
  ADD COLUMN IF NOT EXISTS launch_checklist text[] NOT NULL DEFAULT '{}';

-- Short AI-style summary of the packet (generated by rules-based logic)
ALTER TABLE public.build_packets
  ADD COLUMN IF NOT EXISTS ai_summary text;

-- Recommended page sections for the creator
ALTER TABLE public.build_packets
  ADD COLUMN IF NOT EXISTS suggested_page_sections text[] NOT NULL DEFAULT '{}';

-- Mutable timestamp (missing from original schema)
ALTER TABLE public.build_packets
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();


-- ─── 3. deliverables — expand for pipeline ────────────────────────────────────

-- GitHub repo link for the build
ALTER TABLE public.deliverables
  ADD COLUMN IF NOT EXISTS github_url text;

-- Delivery status lifecycle
ALTER TABLE public.deliverables
  ADD COLUMN IF NOT EXISTS delivery_status text NOT NULL DEFAULT 'draft';

-- Explicit creator_profile_id (creator_id is already a FK to creator_profiles,
--   but naming it explicitly makes joins more readable)
ALTER TABLE public.deliverables
  ADD COLUMN IF NOT EXISTS creator_profile_id uuid
    REFERENCES public.creator_profiles(id) ON DELETE SET NULL;

-- Mutable timestamp
ALTER TABLE public.deliverables
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();


-- ─── 4. DEV-ONLY RLS policies ─────────────────────────────────────────────────
-- ⚠️  WARNING: These policies grant full anonymous + authenticated access.
-- ⚠️  They are UNSAFE for production.
-- ⚠️  Replace with proper per-user policies before deploying publicly.
-- ⚠️  Label: TEMP DEV — remove before production.

-- Enable RLS (no-op if already enabled)
ALTER TABLE public.orders      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.build_packets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deliverables  ENABLE ROW LEVEL SECURITY;

-- orders: full access (DEV ONLY)
DROP POLICY IF EXISTS "dev_orders_full_access" ON public.orders;
CREATE POLICY "dev_orders_full_access"            -- TEMP DEV — UNSAFE
  ON public.orders FOR ALL
  TO anon, authenticated
  USING (true) WITH CHECK (true);

-- build_packets: full access (DEV ONLY)
DROP POLICY IF EXISTS "dev_build_packets_full_access" ON public.build_packets;
CREATE POLICY "dev_build_packets_full_access"     -- TEMP DEV — UNSAFE
  ON public.build_packets FOR ALL
  TO anon, authenticated
  USING (true) WITH CHECK (true);

-- deliverables: full access (DEV ONLY)
DROP POLICY IF EXISTS "dev_deliverables_full_access" ON public.deliverables;
CREATE POLICY "dev_deliverables_full_access"      -- TEMP DEV — UNSAFE
  ON public.deliverables FOR ALL
  TO anon, authenticated
  USING (true) WITH CHECK (true);

-- ─── Done ─────────────────────────────────────────────────────────────────────
-- After running this migration, run npm run build to confirm TypeScript is happy.
-- The dev app will now be able to:
--   - Create orders from buyer requests (Admin → Create Project button)
--   - Assign creators to orders
--   - Update order pipeline status
--   - Creators can see assigned projects in their dashboard
--   - Buyers can see project status linked to their requests
